runtime: python
env: flex

entrypoint: gunicorn -b :$PORT app:app
runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app


#resources:
#  cpu: .5
#  memory_gb: 0.18
#  disk_size_gb: 10